const enTranslation = {
  "title": "Russian Travel",
  "lead-heading": "Russian Travel",
  "lead-subheading": "The real country is not in the news, but here.",
  "lead-caption": "your shelf is the top one",
  "intro-heading": "What we didn't see there?",
  "intro-subheading": "According to VCIOM polls, 95% of Russians dream of traveling somewhere, but only 36% plan to spend their holidays in their home country. Like, what haven’t we seen here at home? In fact, Russia is a whole universe with the gentle sea of the south, the dense forests of the Sayan Mountains and the harsh ice of the Putorana plateau. And you can see all these beauties without millions in your account, a foreign passport and many hours of flights. Like, for example, Vera Bashmakova, a brave young mother who grabbed three children, put them in her Lada and drove 20 thousand kilometers around her native country. We have selected and described some interesting places worthy of your holiday.",
  "intro-timezones": "Timezones",
  "intro-natural-heritage": "UNESCO Natural Heritage Sites",
  "intro-cultural-heritage": "UNESCO cultural heritage sites",
  "intro-parks": "Nature reserves",
  "intro-airports": "Airports",
  "spit-heading": "Curonian Spit",
  "spit-first-paragraph": "Here, among forests and sand dunes, you can see two water horizons - the calm Curonian Lagoon on one side and the rippling Baltic Sea on the other. A unique natural area on the edge of the Russian enclave.",
  "spit-second-paragraph": "The Kaliningrad region does not end there. For the traveler and researcher, in the same neighborhood there is the westernmost point of Russia, the Baltic Spit, and the German heritage of a scattering of small coastal towns. The atmosphere of these places eliminates fuss, immersing you in the tranquility of nature and the smell of the steel, cool sea.",
  "polyana-heading": "Krasnaya Polyana",
  "polyana-link": "Reserve",
  "polyana-first-paragraph": "When coming to Sochi on vacation, many tourists also try to visit Krasnaya Polyana. This is all thanks to the huge number of iconic places and entertainment available here at any time of the year. In winter, the mountain resort is occupied by skiers and snowboarders, and in summer people come to Krasnaya Polyana to go trekking, hiking and mountaineering, as well as explore numerous natural key places.",
  "polyana-second-paragraph": "Krasnaya Polyana is a territory full of key places that one visit may not be enough to explore. Some will be inspired by the local nature, some by the history of ancient civilizations, and others by the opportunity to breathe fresh mountain air.",
  "altai-heading": "Altai",
  "altai-first-paragraph": "Altai is one of the most beautiful places in Russia. First of all, because of the mountains: if you drive along the ridge, you will see slopes strewn with pine trees, mountain rivers and lakes. And if you open the windows in your car, you can get acquainted with the invisible miracle of these places - the mountain air.",
  "altai-second-paragraph": "The climate in Altai is moderate, so it is best to go here in the summer. This way you will see all the diversity of local flora and fauna. Elks roam the forests of Altai, eagles fly over the ridges, and roe deer graze on the plains. And the famous manuls is also an inhabitant of the Altai region.",
  "baikal-heading": "Winter Baikal",
  "bailkal-first-paragraph": "Everyone knows Baikal as the largest lake in the world. Many also know that this is the largest source of fresh water and one of the most beautiful places in Russia.",
  "bailkal-second-paragraph": "Of course, this is all true. But Baikal is also an ideal place for skioring competitions. This is a sport where a skier straps himself to a motorcycle and the tandem tries to develop as much speed as possible on the ice. In March 2019, at the Baikal Mile festival, a world record was set - 197.011 km/h.",
  "karelia-heading": "Karelia",
  "karelia-paragraph": "Siberia ends not in the Urals, but in Karelia: the Siberian larch that forms the taiga does not grow west of Vodlozero. But here it reaches 30 meters — the forests of Karelian national parks have never seen an axe, due to impenetrable swamps. Some pine trees are already more than half a millennium old. Touch a living creature that saw the sun before Ivan the Terrible saw it. In a virgin forest you won’t find a trail for a hundred kilometers. And on rare paths, trees a couple of meters from the ground are marked with bear claws. So that everyone knows who is the boss here.",
  "cover-heading": "To Baikal «on dogs»",
  "cover-subheading": "Based on the educational topic about the Trans-Siberian Railway - a journey from the capital to Lake Baikal by train.",
  "maps": "Maps",
  "weather": "Weather",
  "schedule": "Schedule",
  "calendar": "Calendar",
  "trips": "Trips",
  "copyright": "© 2023. Danilova Maria"
}

export default enTranslation;
